### ISSUE TITLE
Warnings-i v poročilu

### ISSUE THREAD

**Issue by Charisa** [Charisa/APPR-2015-16#6]
Pri knit-anju PDF-ja mi v poglavju Vizualizacija za vsak zemljevid napiše še warningse, ki pa se jih na noben način ne morem znebiti. Je možno, da mi ne izpiše teh zadev?

**Comment by jaanos** [comment]
Bloku, kjer kličeš `vizualizacija.r`, dodaj še parameter `results = 'hide'`.
